server:
  port: '9001'


  spring:
    application:
      name:

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/expenses
    password: JY@class4579
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'

